index:
    path: /
    controller: App\Controller\TechNews\IndexController::index

# RedirectController will redirect without going through a personalised controller.
accueil:
  path: /accueil
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: index
    permanent: true

# Avoids to create a personalised controller
# for our static pages: Contacts, Presentation, Mentions legales, ..
mentions_legales:
  path: /mentions-legales
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/mentionslegales.html.twig